#!/usr/bin/perl -w
use strict;

=pod

FIXME
    * <title> should not be hardcoded

=cut

my $WIDTH = 79;
my $PAGE_HEAD = <<"EOF";
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=en> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang=en> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang=en> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=en> <!--<![endif]-->
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Suffix Guide &ndash; Klingon Pocket Dictionary &ndash; Klingonska Akademien</title>
  <meta name=viewport content="width=device-width">
  <link rel=stylesheet href="../includes/base.css">
  <link rel=stylesheet href="../includes/dict-layouttable.css">
  <link rel=stylesheet href="../includes/dict-suffixguide.css">
  <link rel=stylesheet href="../includes/dict.css">
  <link rel=icon href="/favicon.ico">
  <link rel=canonical href="http://klingonska.org/dict/suffix.html">
  <script src="../includes/modernizr-2.5.3.js"></script>
</head>
<body lang=en itemscope itemtype="http://schema.org/WebPage">

<header role=banner>
  <!-- begin:status -->
  <ul>
    <li>
      <nav itemprop=breadcrumb role=navigation>
        <a href="http://klingonska.org/">Home</a> &gt;
        <a href="http://klingonska.org/dict/">Klingon Pocket Dictionary</a> &gt;
        <a href="http://klingonska.org/dict/suffix.html">Suffix Guide</a>
      </nav>
    </li>
    <li>
      Updated <time pubdate datetime="2012-11-10T00:50">November 10, 2012</time>
    </li>
  </ul>
  <!-- end:status -->
  <div>
    <a href="../">
      <table id=logotitle>
        <td>
          <span class=crop>
            <img height=200 width=200 src="../pic/ka-logo.svg" alt="Klingonska Akademien">
          </span>
        </td>
        <td>
          <h1>Klingonska<span id=logospace>&nbsp;</span>Akademien</h1>
        </td>
      </table>
    </a>
  </div>
</header>

<article role=main itemprop=mainContentOfPage>
  <nav role=navigation class=tabs>
    <a href="about.html">About</a>
    <a href="intro.html">Introduction</a>
    <a href="./">Lexicon</a>
    <span>Suffix Guide</span>
    <a href="tables.html">Reference Tables</a>
  </nav>

<h1>Klingon Pocket Dictionary: Suffix Guide</h1>

<aside class=note>The last pages of text from the book.</aside>
EOF

my $PAGE_FOOT = <<"EOF";
</article>

<footer role=contentinfo>
  <p class=copyright>©<time itemprop=copyrightYear>1998</time>&ndash;<time>2012</time> by
    <a href="mailto:zrajm\@klingonska.org" rel=author itemprop=author>Zrajm C Akfohg</a>,
    <a href="http://klingonska.org/" itemprop=sourceOrganization>Klingonska Akademien</a>, Uppsala
  </p>
  <p class=validator>
    Validate:
    <a href="http://validator.w3.org/check?uri=http://klingonska.org/">HTML5</a>,
    <a href="http://jigsaw.w3.org/css-validator/validator?uri=http://klingonska.org/&amp;profile=css3">CSS3</a>,
    <a href="http://validator.w3.org/checklink?uri=http://klingonska.org/">links</a>.
    License:
    <a href="http://creativecommons.org/licenses/by-sa/3.0/" rel=license>CC BY&ndash;SA</a>.&nbsp;
  </p>
</footer>
<script>var _gaq=[['_setAccount','UA-5434527-2'],['_trackPageview']];
(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
s.parentNode.insertBefore(g,s)}(document,'script'))</script>
<script src="../includes/titlewrap.js"></script>
</body>
</html>
EOF

{
    blockquote      => sub { "<blockquote>" . shift() . "</blockquote>\n\n" },
    bulletlist      => sub { "<ul>" . shift() . "</ul>\n\n" },
    bulletlist_item => sub { "<li>" . shift() . "</li>\n" },
    code            => sub { "<code>" . shift() . "</code>" },
    doublequote     => sub { "&ldquo;" . shift() . "&rdquo;" },
    emdash          => sub { "&mdash;" },
    emphasis        => sub { "<em>" . shift() . "</em>" },
    endash          => sub { "&ndash;" },
    section         => sub { "\n<section>" . shift() . "</section>\n" },
    head1           => sub { "\n" . wrap("<h2>" . shift() . "</h2>", $WIDTH) . "\n\n" },
    head2           => sub { wrap("<h2>" . shift() . "</h2>", $WIDTH) . "\n\n" },
    head3           => sub { wrap("<h3>" . shift() . "</h3>", $WIDTH) . "\n\n" },
    head4           => sub { wrap("<h4>" . shift() . "</h4>", $WIDTH) . "\n\n" },
    head5           => sub { wrap("<h5>" . shift() . "</h5>", $WIDTH) . "\n\n" },
    head6           => sub { wrap("<h6>" . shift() . "</h6>", $WIDTH) . "\n\n" },
    hr              => sub { "<hr>\n\n" },
    html            => sub { shift() . "\n\n" },
    numberlist      => sub { "<ol>" . shift() . "</ol>\n\n" },
    numberlist_item => sub { "<li>" . shift() . "</li>\n\n" },
    paragraph       => sub { wrap("<p>" . shift() . "</p>", $WIDTH) . "\n\n" },
    plain           => sub { use HTML::Entities; encode_entities(shift(), "<>&") },
    root            => sub { $PAGE_HEAD . shift() . $PAGE_FOOT },
    bold            => sub { "<b>" . shift() . "</b>" },
    verbatim        => sub { "<pre>" . shift() . "</pre>\n\n" },

    # KA-specific
    english         => sub { '<i class=translation>' . shift() . '</i>' },
    klingon         => sub { #'<b lang=tlh>' . shift() . '</b>';
                             my ($_) = @_;
                             my $class = (m#(?:^-|-$)# ? ' class=nobr' : '');
                             "<b$class lang=tlh>" . regex(
                                 hyphenate_tlh($_, "&shy;", "-"),
                                 qr/'/,
                                 "&rsquo;",
                             ) . "</b>"
                           },
    reference       => sub { '<small class=ref>[' . regex(shift(), qr/ /, " ") . ']</small>' },
    suffix_guide    => sub { nl('<table class="suffixguide noborder">', shift() . '</table>') },
    sg_section1 => sub { indent(nl(
        '<tr class=head1>',
        '  <td colspan=2>' . shift() . '</td>',
        '</tr>',
    ), '  ') },
    sg_section2 => sub { indent(nl(
        '<tr class=head2>',
        indent(shift() . '</td>', '  '),
        '</tr>',
    ), '  ') },
    sg_section3 => sub { indent(nl(
        '<tr class=head3>',
        shift() . '</td>',
        '</tr>',
    ), '  ') },
    sg_head1 => sub { '<h3>' . shift() . '</h3>' },
    sg_head2 => sub { shift() },
    sg_head3 => sub { indent(
        "<td></td>\n" .
        wrap('<td><h3>' . shift() . '</h3>', $WIDTH-2),
        '  ',
    ) },
    sg_paragraph => sub { "\n" . indent(nl(
        wrap('<p>' . shift() . '</p>', $WIDTH-2, $WIDTH-4),
    ), '  ', '    ') },
        sg_head1_type      => sub { '<span class=type>' . shift() . '.</span>' },
        sg_head1_text      => sub { shift() . nl() },
        sg_head1_reference => sub { '    ' . shift() },
        sg_head2_klingon   => sub { nl('<td valign=top>' . shift() . '</td>') },
        sg_head2_english   => sub { '<td>' . shift() },
        sg_head2_reference => sub { ' ' . shift() },
}

#[eof]
