#!/usr/bin/perl

use warnings;
use strict;
use feature ":5.10";

my $WIDTH = 79;
my $PAGE_HEAD = <<"EOF";
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML><HEAD><TITLE>Suffix Guide &ndash; Klingon Pocket Dictionary &ndash; Klingonska Akademien</TITLE>
</HEAD>
<BODY VLINK="#777777" ALINK="#AAAAAA" LINK="#444444" TEXT="#000000" BGCOLOR="#FFFFFF">


<TABLE BORDER=0 CELLPADDING=1 CELLSPACING=0 WIDTH="100%">
<TR><TD VALIGN=TOP>


<!-- ==================== Title. ==================== -->
<center>
<a href="../"><img src="pic/title.gif" width="400" height="166" alt="tlhIngan Hol mu'ghom mach" border=0></a>
<h1>Klingon Pocket Dictionary: Suffix Guide</h1>
<p>
  <table align=center bgcolor="#BBBBBB" cellpadding=5>
    <tr>
      <td align=center><b>The last pages of text from the book.</b></td>
    </tr>
  </table> 
</center>
EOF
my $PAGE_FOOT = <<"EOF";



<!-- ==================== Copyright ==================== -->
<P><CENTER><TABLE CELLPADDING=0 CELLSPACING=0 BORDER=0>
  <TR>
    <TD VALIGN=BOTTOM COLSPAN=3><HR NOSHADE></TD>
  </TR>
  <TR>
    <TD>         </TD>
    <TD ALIGN=CENTER><B>©1998-2002, Copyright 
      <A HREF="mailto:zrajm\@klingonska.org">Zrajm C Akfohg</A>, 
      <A HREF="http://klingonska.org/">Klingonska Akademien</A>, Uppsala.</B></TD>
    <TD>         </TD>
  </TR>
  <TR>
    <TD VALIGN=TOP COLSPAN=3><HR NOSHADE></TD>
  </TR>
</TABLE>


<!-- ================== Feedback Form ================== -->
<!-- [2007-07-15] Below stuff disabled in move to ManuFrog -->
<!-- (remove spaces before "#" to re-enable) -->
<!-- #include virtual="/feedback.cgi"
--><!-- #if expr="!\$X_NOLOG"
  --><!-- #include virtual="/.log.cgi"
--><!-- #endif -->
</CENTER>
</BODY>
</HTML>

</TD>

<!-- ==================== Navigation flaps ==================== -->
<TD VALIGN=TOP><TABLE CELLSPACING=2 CELLPADDING=0>
  <TR><TD><A HREF="./"               ><IMG
    SRC="pic/about.gif"   WIDTH=21 HEIGHT=65  ALT="About"            BORDER=2></A></TD>
  </TR><TR><TD><A HREF="intro.html"  ><IMG
    SRC="pic/intro.gif"   WIDTH=21 HEIGHT=124 ALT="Introduction"     BORDER=2></A></TD>
  </TR><TR><TD><A HREF="lexicon.cgi"><IMG
    SRC="pic/lexicon.gif" WIDTH=21 HEIGHT=84  ALT="Lexicon"          BORDER=2></A></TD>
  </TR><TR><TD                       ><IMG
    SRC="pic/suffix.gif"  WIDTH=21 HEIGHT=128 ALT="Suffix Guide"     BORDER=0></TD>
  </TR><TR><TD><A HREF="tables.html" ><IMG
    SRC="pic/tables.gif"  WIDTH=21 HEIGHT=180 ALT="Reference Tables" BORDER=2></A></TD>
  </TR>
</TABLE></TD></TR></TABLE>
</BODY></HTML>
EOF

my $SUFFIX_GUIDE_HEAD = <<'EOF';

EOF



{
    blockquote      => sub { "<blockquote>" . shift() . "</blockquote>\n\n" },
    bulletlist      => sub { "<ul>" . shift() . "</ul>\n\n" },
    bulletlist_item => sub { "<li>" . shift() . "</li>\n" },
    code            => sub { "<code>" . shift() . "</code>" },
    doublequote     => sub { "&ldquo;" . shift() . "&rdquo;" },
    emdash          => sub { "&mdash;" },
    emphasis        => sub { "<em>" . shift() . "</em>" },
    endash          => sub { "&ndash;" },
    head1           => sub { "\n" . wrap("<h2>" . shift() . "</h2>", $WIDTH) . "\n\n" },
    head2           => sub { wrap("<h2>" . shift() . "</h2>", $WIDTH) . "\n\n" },
    head3           => sub { wrap("<h3>" . shift() . "</h3>", $WIDTH) . "\n\n" },
    head4           => sub { wrap("<h4>" . shift() . "</h4>", $WIDTH) . "\n\n" },
    head5           => sub { wrap("<h5>" . shift() . "</h5>", $WIDTH) . "\n\n" },
    head6           => sub { wrap("<h6>" . shift() . "</h6>", $WIDTH) . "\n\n" },
    hr              => sub { "<hr>\n\n" },
    html            => sub { shift() . "\n\n" },
    numberlist      => sub { "<ol>" . shift() . "</ol>\n\n" },
    numberlist_item => sub { "<li>" . shift() . "</li>\n\n" },
    paragraph       => sub { wrap("<p>" . shift() . "</p>", $WIDTH) . "\n\n" },
    plain           => sub { use HTML::Entities; encode_entities(shift(), "<>&") },
    root            => sub { $PAGE_HEAD . shift() . $PAGE_FOOT },
    bold            => sub { "<b>" . shift() . "</b>" },
    verbatim        => sub { "<pre>" . shift() . "</pre>\n\n" },

    # KA-specific
    english         => sub { '<i>' . shift() . '</i>' 
                                 #"<em class=\"en\">" . shift() . "</em>"
                           },
    klingon         => sub { '<b lang="tlh">' . shift() . '</b>';
                                 # "<b lang=\"tlh\">" . regex(
                                 #     hyphenate_tlh(shift(), "&shy;"),
                                 #     qr/'/,
                                 #     "&rsquo;"
                                 # ) . "</b>"
                           },
    reference       => sub { '<font size=2>[' . regex(shift(), qr/ /, " ") . ']</font>'
                             #"<small class=\"ref\">[" . shift() . "]</small>"
    },
    suffix_guide    => sub { nl(
        '<table border=0 cellpadding=0 cellspacing=0 width=75% align=center>',
        shift(),
        '  <tr>',
        '    <td colspan=6 height=2 bgcolor=black><img src="pic/spacer.gif" width=2 height=2></td>',
        '  </tr>',
        '</table> ',
    ) },
    #sg_div1         => sub { '<hr>' . shift() . '<hr>' },
    sg_div1 => sub { shift() },
    #sg_div2 => sub { shift() },
    sg_head1 => sub { nl(
        '  <tr>',
        '    <td colspan=6 height=2 bgcolor=black><img src="pic/spacer.gif" width=2 height=2></td>',
        '  </tr>',
        '  <tr valign=top>',
        '    <td width=2 bgcolor=black><img src="pic/spacer.gif" width=2 height=2></td>',
        shift(),
        '    <td width=2 bgcolor=black><img src="pic/spacer.gif" width=2 height=2></td>',
        '  </tr>',
    ) },
    sg_head2 => sub { shift() },
    sg_div2 => sub { nl(
        '  <tr valign=top>',
        '    <td width=2 bgcolor=black><img src="pic/spacer.gif" width=2 height=2></td>',
        '    <td></td>',
        shift() . '</td>',
        '    <td width=2 bgcolor=black><img src="pic/spacer.gif" width=2 height=2></td>',
        '  </tr>',
    ) },
    sg_head3        => sub { wrap('<h3 class="sg">' . shift() . "</h3>", $WIDTH) . "\n\n" },
    sg_paragraph    => sub {
        "<br>\n" .
        indent(wrap('<font size=2>' . shift() . '</font>', 64, 62), '      ', '        ');
    },

        sg_head1_type      => sub { nl('    <td><font size=4> ' . shift() . '. </font></td>') },
        sg_head1_text      => sub { nl('    <td colspan=2><font size=4>' . shift() . '</font></td>') },
        sg_head1_reference => sub {    '    <td align=right>' . shift() . ' </td>' },
        sg_head2_klingon   => sub { nl('    <td>' . shift() . '</td>') },
        sg_head2_english   => sub {    '    <td colspan=2>' . shift() },
        sg_head2_reference => sub {    ' ' . shift() },
}

#[eof]
