#!/usr/bin/perl -w
use strict;

=pod

FIXME
    * <title> should not be hardcoded

=cut

my $WIDTH = 79;
my $PAGE_HEAD = <<"EOF";
<!DOCTYPE html>
<!-- Copyright 1998–2022 by zrajm. License: CC BY-SA (text), GPLv2 (code) -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Suffix Guide &ndash; Klingon Pocket Dictionary &ndash; Klingonska Akademien</title>
<link rel=stylesheet href="../includes/base.css">
<link rel=stylesheet href="../includes/dict-layouttable.css">
<link rel=stylesheet href="../includes/dict-suffixguide.css">
<link rel=stylesheet href="../includes/dict.css">
<link rel=stylesheet href="../includes/pagetabs.css">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#bb3333">
<meta name="msapplication-TileColor" content="#bb3333">
<meta name="theme-color" content="#bb3333">
<link rel=canonical href="http://klingonska.org/dict/suffix.html">
<header role=banner class=tabbed>
  <!-- begin:status -->
  <ul>
    <li>
      <nav itemprop=breadcrumb role=navigation>
        <a href="http://klingonska.org/">Home</a> &gt;
        <a href="http://klingonska.org/dict/">Klingon Pocket Dictionary</a> &gt;
        <a href="http://klingonska.org/dict/suffix.html">Suffix Guide</a>
      </nav>
    <li>
      Updated <time pubdate datetime="2022-07-10T12:08+02:00">July 10, 2022</time>
  </ul>
  <!-- end:status -->
  <div>
    <a href="../">
      <table id=logotitle>
        <td>
          <span class=crop>
            <img height=200 width=200 src="../pic/ka-logo.svg" alt="Klingonska Akademien">
          </span>
        <td>
          <h1>Klingonska<span id=logospace>&nbsp;</span>Akademien</h1>
      </table>
    </a>
    <nav class=pagetabs role=navigation>
      <a href="about.html">About</a>
      <a href="intro.html">Introduction</a>
      <a href="./">Lexicon</a>
      <span class=selected>Suffix Guide</span>
      <a href="tables.html">Reference Tables</a>
    </nav>
  </div>
</header>

<article role=main itemprop=mainContentOfPage style="padding-top:1px">
<h1>Klingon Pocket Dictionary: Suffix Guide</h1>

<aside class=note>The last pages of text from the book.</aside>
EOF

my $PAGE_FOOT = <<"EOF";
</article>

<footer role=contentinfo>
  <p class=copyright>© <time itemprop=copyrightYear>1998</time>&ndash;<time>2022</time> by
    <a href="mailto:zrajm\@klingonska.org" rel=author itemprop=author>zrajm</a>,
    <a href="http://klingonska.org/" itemprop=sourceOrganization>Klingonska Akademien</a>, Uppsala
  <p>License: <a href="http://creativecommons.org/licenses/by-sa/3.0/" rel=license>CC BY-SA</a>
</footer>
<script src="../includes/titlewrap.js"></script>
<!--[eof]-->
EOF

{
    blockquote      => sub { "<blockquote>" . shift() . "</blockquote>\n\n" },
    bulletlist      => sub { "<ul>" . shift() . "</ul>\n\n" },
    bulletlist_item => sub { "<li>" . shift() . "\n" },
    code            => sub { "<code>" . shift() . "</code>" },
    doublequote     => sub { "&ldquo;" . shift() . "&rdquo;" },
    emdash          => sub { "&mdash;" },
    emphasis        => sub { "<em>" . shift() . "</em>" },
    endash          => sub { "&ndash;" },
    section         => sub { "\n<section>" . shift() . "</section>\n" },
    head1           => sub { "\n" . wrap("<h2>" . shift() . "</h2>", $WIDTH) . "\n\n" },
    head2           => sub { wrap("<h2>" . shift() . "</h2>", $WIDTH) . "\n\n" },
    head3           => sub { wrap("<h3>" . shift() . "</h3>", $WIDTH) . "\n\n" },
    head4           => sub { wrap("<h4>" . shift() . "</h4>", $WIDTH) . "\n\n" },
    head5           => sub { wrap("<h5>" . shift() . "</h5>", $WIDTH) . "\n\n" },
    head6           => sub { wrap("<h6>" . shift() . "</h6>", $WIDTH) . "\n\n" },
    hr              => sub { "<hr>\n\n" },
    html            => sub { shift() . "\n\n" },
    numberlist      => sub { "<ol>" . shift() . "</ol>\n\n" },
    numberlist_item => sub { "<li>" . shift() . "\n\n" },
    paragraph       => sub { wrap("<p>" . shift() . "</p>", $WIDTH) . "\n\n" },
    plain           => sub { use HTML::Entities; encode_entities(shift(), "<>&") },
    root            => sub { $PAGE_HEAD . shift() . $PAGE_FOOT },
    bold            => sub { "<b>" . shift() . "</b>" },
    verbatim        => sub { "<pre>" . shift() . "</pre>\n\n" },

    # KA-specific
    english         => sub { '<i class=translation>' . shift() . '</i>' },
    klingon         => sub { #'<b lang=tlh>' . shift() . '</b>';
                             local ($_) = @_;
                             my $class = (m#(?:^-|-$)# ? ' class=nobr' : '');
                             "<b$class lang=tlh>" . regex(
                                 hyphenate_tlh($_, "­", "-"),
                                 qr/'/,
                                 "&rsquo;",
                             ) . "</b>"
                           },
    reference       => sub { '<small class=ref>[' . regex(shift(), qr/ /, " ") . ']</small>' },
    suffix_guide    => sub { nl('<table class="suffixguide noborder">', shift() . '</table>') },
    sg_section1 => sub { indent(nl(
        '<tr class=head1>',
        '  <td colspan=2>' . shift(),
    ), '  ') },
    sg_section2 => sub { indent(nl(
        '<tr class=head2>',
        indent(shift(), '  '),
    ), '  ') },
    sg_section3 => sub { indent(nl(
        '<tr class=head3>',
        shift(),
    ), '  ') },
    sg_head1 => sub { '<h3>' . shift() . '</h3>' },
    sg_head2 => sub { shift() },
    sg_head3 => sub { indent(
        "<td>\n" .
        wrap('<td><h3>' . shift() . '</h3>', $WIDTH-2),
        '  ',
    ) },
    sg_paragraph => sub { "\n" . indent(nl(
        wrap('<p>' . shift() . '</p>', $WIDTH-2, $WIDTH-4),
    ), '  ', '    ') },
        sg_head1_type      => sub { '<span class=type>' . shift() . '.</span>' },
        sg_head1_text      => sub { shift() . nl() },
        sg_head1_reference => sub { '    ' . shift() },
        sg_head2_klingon   => sub { nl('<td valign=top>' . shift()) },
        sg_head2_english   => sub { '<td>' . shift() },
        sg_head2_reference => sub { ' ' . shift() },
}

#[eof]
