#!/usr/bin/perl -w
use strict;

=pod

FIXME
    * <title> should not be hardcoded

=cut

my $WIDTH = 79;
my $PAGE_HEAD = <<"EOF";
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Suffix Guide &ndash; Klingon Pocket Dictionary &ndash; Klingonska Akademien</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="geo.region" content="SE-C" />
<meta name="geo.placename" content="Europe, Sweden, Uppsala, Kåbo" />
<meta name="geo.position" content="59.845658;17.630797" />
<link rel="stylesheet" type="text/css" href="../includes/dict-layouttable.css" />
<link rel="stylesheet" type="text/css" href="../includes/dict-suffixguide.css" />
<link rel="stylesheet" type="text/css" href="../includes/dict.css" />
<link rel="stylesheet" type="text/css" href="../includes/page.css" />
<link rel="stylesheet" type="text/css" href="../includes/pagestats.css" />
</head>
<body>

<div id="head">
<!-- begin:status -->
<div id="pagestats">
  <span id="crumbs">
    <a href="http://klingonska.org/">Home</a> &gt;
    <a href="http://klingonska.org/dict/">Klingon Pocket Dictionary</a> &gt;
    <a href="http://klingonska.org/dict/suffix.html">Suffix Guide</a>
  </span>
  <span id="pubdate">
    Updated <time pubdate datetime="2009-10-18T20:17">October 18, 2009</time>
  </span>
</div>
<!-- end:status -->

<table class="navigation">
  <tr>
    <td><a href="./">About</a></td>
    <td><a href="intro.html">Introduction</a></td>
    <td><a href="lexicon.cgi">Lexicon</a></td>
    <td><strong>Suffix Guide</strong></td>
    <td><a href="tables.html">Reference Tables</a></td>
  </tr>
</table>

<a href=".."><img src="pic/title.gif" width="400" height="166" alt="tlhIngan Hol mu'ghom mach" /></a>

<h1>Klingon Pocket Dictionary: Suffix Guide</h1>

<p class="note">The last pages of text from the book.</p>
</div>

<div id="main">
EOF

my $PAGE_FOOT = <<"EOF";
</div>

<div id="foot">
<p class="copyright">©1998&ndash;2010, Copyright <!-- FIXME autogenerate dates -->
<span class="author"><a href="mailto:zrajm\@klingonska.org">Zrajm C Akfohg</a></span>,
<a href="http://klingonska.org/">Klingonska Akademien</a>, Uppsala.</p>
<p class="validator">
  Validate:
  <a href="http://validator.w3.org/check?uri=http://klingonska.org/dict/suffix.html">XHTML</a>,
  <a href="http://jigsaw.w3.org/css-validator/validator?uri=http://klingonska.org/dict/suffix.html&amp;profile=css3">CSS3</a>,
  <a href="http://validator.w3.org/checklink?uri=http://klingonska.org/dict/suffix.html">links</a>.
  License:
  <a href="http://creativecommons.org/licenses/by-sa/3.0/" rel="license">CC BY&ndash;SA</a>.&nbsp;
</p>
</div>
</body>
</html>
EOF

{
    blockquote      => sub { "<blockquote>" . shift() . "</blockquote>\n\n" },
    bulletlist      => sub { "<ul>" . shift() . "</ul>\n\n" },
    bulletlist_item => sub { "<li>" . shift() . "</li>\n" },
    code            => sub { "<code>" . shift() . "</code>" },
    doublequote     => sub { "&ldquo;" . shift() . "&rdquo;" },
    emdash          => sub { "&mdash;" },
    emphasis        => sub { "<em>" . shift() . "</em>" },
    endash          => sub { "&ndash;" },
    head1           => sub { "\n" . wrap("<h2>" . shift() . "</h2>", $WIDTH) . "\n\n" },
    head2           => sub { wrap("<h2>" . shift() . "</h2>", $WIDTH) . "\n\n" },
    head3           => sub { wrap("<h3>" . shift() . "</h3>", $WIDTH) . "\n\n" },
    head4           => sub { wrap("<h4>" . shift() . "</h4>", $WIDTH) . "\n\n" },
    head5           => sub { wrap("<h5>" . shift() . "</h5>", $WIDTH) . "\n\n" },
    head6           => sub { wrap("<h6>" . shift() . "</h6>", $WIDTH) . "\n\n" },
    hr              => sub { "<hr>\n\n" },
    html            => sub { shift() . "\n\n" },
    numberlist      => sub { "<ol>" . shift() . "</ol>\n\n" },
    numberlist_item => sub { "<li>" . shift() . "</li>\n\n" },
    paragraph       => sub { wrap("<p>" . shift() . "</p>", $WIDTH) . "\n\n" },
    plain           => sub { use HTML::Entities; encode_entities(shift(), "<>&") },
    root            => sub { $PAGE_HEAD . shift() . $PAGE_FOOT },
    strong          => sub { "<strong>" . shift() . "</strong>" },
    verbatim        => sub { "<pre>" . shift() . "</pre>\n\n" },

    # KA-specific
    english         => sub { '<em class="translation">' . shift() . '</em>' 
                                 #"<em class=\"en\">" . shift() . "</em>"
                           },
    klingon         => sub { #'<strong lang="tlh">' . shift() . '</strong>';
                             '<strong lang="tlh">' . regex(
                                 klinhyphenate(shift(), "&shy;", "-"),
                                 qr/'/,
                                 "&rsquo;"
                             ) . "</strong>"
                           },
    reference       => sub { '<small class="ref">[' . regex(shift(), qr/ /, " ") . ']</small>' },
    suffix_guide    => sub { nl('<table class="suffixguide" border="1">', shift(), '</table>') },
    sg_head1 => sub { nl(
        '<tr class="head1">',
        '  <td colspan="2"><h3>' . shift() . '</h3></td>',
        '</tr>',
        '',
    ) },
    sg_head2 => sub { nl('<tr class="head2">', shift()) },
    sg_head3 => sub { nl(
        '<tr class="head3">',
        '  <td></td>',
        indent(wrap('<td><h3>' . shift() . '</h3>', $WIDTH-2), '  '),
        ''
    ) },
    sg_paragraph    => sub { nl(
        indent(wrap('<p>' . shift() . '</p>', $WIDTH-2, $WIDTH-4), '  ', '    '),
        '',
    ) },
        sg_head1_type      => sub { '<span class="type">' . shift() . '.</span>' },
        sg_head1_text      => sub { shift() . nl() },
        sg_head1_reference => sub { '    ' . shift() },
        sg_head2_klingon   => sub { nl('  <td valign="top">' . shift() . '</td>') },
        sg_head2_english   => sub { nl('  <td>' . shift()) },
        sg_head2_reference => sub { nl('  ' . shift()) },
}

#[eof]
